version: 0.2
# See http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax for more info.
phases:
  install:
    commands:
      - yum install -y python36-devel
      - pip3 install --upgrade pip
      - pip3 install --upgrade setuptools
      - pip3 install --upgrade wheel
#  pre_build:
#    commands:
#      - echo "I'm a command in the 'pre_build' phase!"
  build:
    commands:
      - python3 setup.py bdist_wheel --universal
#  post_build:
#    commands:
#      - echo "I'm a command in the 'post_build' phase!"
artifacts:
  files:
    - dist/*.whl
  discard-paths: yes